### sklearn.preprocessing 
- 데이터 인코딩 
    - 레이블 인코딩
    - 원-핫 인코딩

### 레이블 인코딩

In [ ]:
## 레이블 인코딩.
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

## LabelEncoder를 객체로 생성한 후 , fit( ), transform( )으로 label 인코딩 수행. 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 클래스:', encoder.classes_)
print('인코딩 변환값:', labels)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
인코딩 변환값: [0 1 4 5 3 3 2 2]

In [ ]:
## 원-핫 인코딩. (사이킷런에서 제공하는 API)
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

## 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환. 
encoder = LabelEncoder() ## 레이블 인코더.
encoder.fit(items)
labels = encoder.transform(items)
## 2차원 데이터로 변환합니다. 
labels = labels.reshape(-1,1)

## 원-핫 인코딩을 적용합니다. 
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터:')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원:')
print(oh_labels.shape)

원-핫 인코딩 데이터:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원:
(8, 6)

### 원-핫 인코딩

In [ ]:
## 원-핫 인코딩. (pandas에서 제공하는 API)
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
pd.get_dummies(df)

   item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

In [ ]:
df

   item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서